In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('fraud_data.csv')
X = df.iloc[:, :-1]
Y = df.iloc[:,-1]
# print(X.head())
# print(Y.head())

In [4]:
x = (Y[ Y == 1 ]).shape[0]/Y.size
print(x*100)

1.6410823768035772


In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, random_state = 0)

In [26]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import recall_score
dummy = DummyClassifier(strategy='most_frequent').fit(x_train, y_train)
pred_d = dummy.predict(x_test)
score_d = dummy.score(x_test,y_test)
recall_d = recall_score(y_test, pred_d)
print("recall: ",recall_d,"\n","acc: ",score_d)

recall:  0.0 
 acc:  0.985250737463


In [31]:
from sklearn.metrics import precision_score
from sklearn.svm import SVC
from sklearn.metrics import recall_score, precision_score
from sklearn.svm import SVC
svc_1 = SVC(C=10, gamma=.001, kernel='rbf').fit(x_train, y_train)
acc_1 = svc_1.score(x_test, y_test)
pred_1 = svc_1.predict(x_test)
recall_1 = recall_score(y_test, pred_1)
score_1 = precision_score(y_test, pred_1)

print("recall: ",recall_1,"\n","acc: ",acc_1, "\n","precision_score: ", score_1)
matrix_1 = confusion_matrix(y_test, pred_1)
matrix_1

recall:  0.75 
 acc:  0.995943952802 
 precision_score:  0.967741935484


array([[5342,    2],
       [  20,   60]])

In [33]:
svcl = SVC().fit(x_train, y_train)
accl = svcl.score(x_test, y_test)
predl = svcl.predict(x_test)
recall_l = recall_score(y_test, pred)
score_l = precision_score(y_test, pred)

print("recall: ",recall_l,"\n","acc: ",accl, "\n","precision_score: ", score_l)
matrix_l = confusion_matrix(y_test, predl)
matrix_l

recall:  0.8 
 acc:  0.990781710914 
 precision_score:  0.941176470588


array([[5344,    0],
       [  50,   30]])

In [10]:
y_decf = svc.decision_function(x_test)
y_decf

array([-1.09285824, -0.83364274, -1.07320874, ..., -1.06259224,
       -1.11065396, -1.05949293])

In [12]:
y_decf_1 = svc.decision_function(x_test)
y_decf_1

array([-1.09285824, -0.83364274, -1.07320874, ..., -1.06259224,
       -1.11065396, -1.05949293])

In [13]:

svc_2 = SVC(C= 1e9, gamma= 1e-07).fit(x_train, y_train)
acc = svc_2.score(x_test, y_test)
pred = svc_2.predict(x_test)
recall = recall_score(y_test, pred)
score = precision_score(y_test, pred)

print("recall: ",recall,"\n","acc: ",acc, "\n","precision_score: ", score)
matrix = confusion_matrix(y_test, pred)

recall:  0.8 
 acc:  0.996312684366 
 precision_score:  0.941176470588


In [24]:

y_decf_2 = svc_2.decision_function(x_test)
# y_decf_2 [y_decf_2 >= 0]
y_score = np.zeros(pred.shape[0])
y_score[ np.where( y_decf_2 >= -220 ) ] = 1
matrix = confusion_matrix(y_test, y_score)

In [25]:
matrix


array([[5320,   24],
       [  14,   66]])

In [ ]:
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_test, y_scores_lr)
for data in zip(precision, recall):
    print(data)
from sklearn.metrics import roc_curve, auc
y_score_lr = lr.fit(X_train, y_train).decision_function(X_test)
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_score_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve, auc

lr = LogisticRegression().fit(x_train, y_train)
y_prob = lr.predict_proba(x_test)
y_des = lr.decision_function(x_test)

In [21]:
precision, recall, threshold = precision_recall_curve(y_test, y_des)
fpr, tpr, _ = roc_curve(y_test, y_des)

In [23]:
print('recall :',recall[np.where(precision == 0.75)] )
print('recall :',tpr[np.where((fpr>= 0.159) & (fpr <= 0.161))] )

recall : [ 0.825]
recall : [ 0.9375  0.95  ]


In [28]:
fpr

array([  0.00000000e+00,   0.00000000e+00,   1.87125749e-04,
         1.87125749e-04,   3.74251497e-04,   3.74251497e-04,
         5.61377246e-04,   5.61377246e-04,   5.23952096e-03,
         5.23952096e-03,   1.47829341e-02,   1.47829341e-02,
         2.69461078e-02,   2.69461078e-02,   4.26646707e-02,
         4.26646707e-02,   6.17514970e-02,   6.17514970e-02,
         7.52245509e-02,   7.52245509e-02,   1.23315868e-01,
         1.23315868e-01,   1.37911677e-01,   1.37911677e-01,
         1.48577844e-01,   1.48577844e-01,   1.59618263e-01,
         1.59618263e-01,   2.04715569e-01,   2.05276946e-01,
         2.16878743e-01,   2.17252994e-01,   2.31287425e-01,
         2.31287425e-01,   2.37836826e-01,   2.37836826e-01,
         2.68899701e-01,   2.69273952e-01,   4.74738024e-01,
         4.75112275e-01,   5.75598802e-01,   5.75598802e-01,
         5.94498503e-01,   5.94498503e-01,   6.83757485e-01,
         6.84131737e-01,   8.69011976e-01,   8.69386228e-01,
         1.00000000e+00]

In [26]:
y_test.shape

(5424,)

In [27]:
y_train.shape

(16269,)

In [30]:

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
params_lr = {
    'penalty': ['l1', 'l2'],
    'C':[0.01, 0.1, 1, 10, 100]
}
grid_lr = GridSearchCV(estimator = LogisticRegression(), param_grid= params_lr, scoring = 'recall', cv = 3,verbose=1, n_jobs=-1)

In [31]:
grid_lr.fit(x_train, y_train)


Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   18.7s finished


GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='recall', verbose=1)

In [32]:
print('Grid best estimator: ', grid_lr.best_estimator_)
print('Grid best parameter (max. accuracy): ', grid_lr.score(x_test, y_test))

Grid best estimator:  LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
Grid best parameter (max. accuracy):  0.8


In [33]:
grid_lr.cv_results_

{'mean_fit_time': array([ 0.65230115,  2.43606559,  1.67400042,  3.86960816,  3.15615622,
         5.17370685,  5.12476556,  5.8850855 ,  5.94351387,  3.76996501]),
 'mean_score_time': array([ 0.30196381,  0.20207183,  0.15891083,  0.46493435,  0.30456487,
         0.12867379,  0.50299215,  0.18525807,  0.16701214,  0.09860603]),
 'mean_test_score': array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
         0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.80797101]),
 'mean_train_score': array([ 0.68115942,  0.77355072,  0.80615942,  0.8134058 ,  0.81884058,
         0.81702899,  0.82427536,  0.82427536,  0.82427536,  0.82427536]),
 'param_C': masked_array(data = [0.01 0.01 0.1 0.1 1 1 10 10 100 100],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_penalty': masked_array(data = ['l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2'],
              mask = [False False False False False False Fals

In [36]:
grid_lr.cv_results_['mean_test_score']

array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
        0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.80797101])

In [37]:
arr = grid_lr.cv_results_['mean_test_score'].reshape([5,2])

In [38]:
# RECALL SCORE
arr

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.80797101]])